[2022-03-25 19:10:24] [ERROR] [Errno 2] No such file or directory: 'd:\\code\\standard_test\\ST_test_frame\\standard_case\\on_board_system\\test_sros_upgrade\\SROS-v4.16.0-352fc27.update'
[2022-03-25 19:19:29] [ERROR] HTTPConnectionPool(host='192.168.33.21', port=80): Max retries exceeded with url: /api/v0/update/import (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000216FF7E0CD0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-03-25 19:19:29] [ERROR] HTTPConnectionPool(host='192.168.33.21', port=80): Max retries exceeded with url: /api/v0/update/import (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000216FF7E0CD0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-03-25 19:19:50] [ERROR] get_system_maintenance:HTTPConnectionPool(host='192.168.33.21', port=80): Max retries exceeded with url: /api/v0/upgrade_record/system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000216FF7B8AC0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-03-25 19:19:50] [ERROR] get_system_maintenance:HTTPConnectionPool(host='192.168.33.21', port=80): Max retries exceeded with url: /api/v0/upgrade_record/system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000216FF7B8AC0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
[2022-03-25 19:19:50] [ERROR] get_system_maintenance:HTTPConnectionPool(host='192.168.33.21', port=80): Max retries exceeded with url: /api/v0/upgrade_record/system (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000216FF7B8AC0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
